development:
    auth:
    adapter: mysql2
    encoding: utf8
    host: db_auth
    username: root
    password: group24
    database: auth
    port: 3307
test:
    auth:
    adapter: mysql2
    encoding: utf8
    host: db_auth
    username: root
    password: group24
    database: auth
    port: 3307
